### ISSUE TITLE
Force metadata update from remote repository.

### ISSUE THREAD

**Issue by Polish-Civil** [shrinkwrap/shrinkwrap#116]
I have remote maven repository that holds maven metadata xml file which provides version list. The metadata is updated and placed on local maven repository (~/.m2)

Problem is when i change the local metadata it doesn't get updated.

So my question is how to force ShrinkWrap to grab metadata from remote and not use local one.

**Comment by ALRubinger** [comment]
Is this issue better suited for ShrinkWrap Resolvers?

https://github.com/shrinkwrap/resolver

**Comment by Polish-Civil** [comment]
Thank you, i wasn't sure where to post it.
