### ISSUE TITLE
Bump Major Version Number: Make ShrinkWrap releasable in modern JVMs

### ISSUE THREAD

**Issue by ALRubinger** [shrinkwrap/shrinkwrap#129]
Umbrella issue. Will link sub-issues in the comments here, and submit fixes for each commit. 

Let's rev ShrinkWrap into the modern age. It used to require:

JRE5+ to run
JDK6+ to build
JRE7+ for optional features

Let's get this to JDK8+ for build and run in a 2.0.0-X release stream. ShrinkWrap should work for all JVMs 8-14.

Things do not build now. Let's allow breaking changes so we can give this project fresh life for a path forward in bug fixes and feature improvements.

PRs to this issue will show passing development locally here in:

```
openjdk version "14.0.2" 2020-07-14
openjdk version "9.0.4"
openjdk version "1.8.0_265"
```

**Comment by ALRubinger** [comment]
Linked Issues:

* #130 
* #131 
* #132 
* #133 

PR is submitted for all in #134.

**Comment by bartoszmajsak** [comment]
> And: can we set up some CI builds for these to test against those JVMs going forward?

I would suggest using circle-ci with several JVMs set up. From my experience, it's way more reliable than Travis these days. I can set it up if that's desired.

Side note: it seems your commits are not matching your gh user :)

**Comment by ALRubinger** [comment]
Done in #134
