### ISSUE TITLE
Rename: "master" branch to "main"

### ISSUE THREAD

**Issue by ALRubinger** [shrinkwrap/shrinkwrap#135]
No code changes required, but likely some maintenance on the CI systems.

For the new work I've submitted in #129 and its linked issues, a good excuse to set the mainline development branch name now?

Ping me if you'd like explanation why.

**Comment by bartoszmajsak** [comment]
We should apply that change to all other repos in this org too. While doing so maybe we should look if there are some repos to archive as well.

**Comment by ALRubinger** [comment]
This is done for `shrinkwrap/shrinkwrap`.
